### ISSUE TITLE
Responsive Issue

### ISSUE THREAD

**Issue by Serpentsoft** [leafo/sticky-kit#142]
Hi All,

As you know there's an issue in responsive mode, the sidebar overlapping on the content because of its position style, so you can solve this issue by modifying the js file just add a CSS class inside the additional div, like so...

```javascript
- Change the following div
(h=null!=p?p&&a.closest(p):b("<div />"))&&h.css("position",a.css("position"))

- With
(h=null!=p?p&&a.closest(p):b("<div class='xyz-insideplugin-sticky' />"))&&h.css("position",a.css("position"))
```

Then change the new CSS class [.xyz-insideplugin-sticky] properties in a responsive state with an important keyword.

like..
```css
@media (min-width: 768px) and (max-width: 979px) {
    .xyz-insideplugin-sticky{
        position: static !important;
        top: auto !important;
        width: auto !important;
        height: auto !important;
        bottom: auto !important;
        float: initial !important;
    }
}
```

Thanks, Hope it's help.
