### ISSUE TITLE
Scrolling stops working in chrome 65

### ISSUE THREAD

**Issue by milansimek** [leafo/sticky-kit#259]
When using sticky kit with chrome 65, scrolling stops working if you scroll constantly starting at page load.

It seems it blocks requestAnimationFrame and async deferred loading of resources.

**Comment by milansimek** [comment]
Found a fix using the following CSS:

```css
.is_stuck {
  transform:translate3d(0,0,0);
}
```
It seems scrolling doesn't work properly in chrome 65 whenever a fixed element is added to the page.
