### ISSUE TITLE
stick to bottom

### ISSUE THREAD

**Issue by cmpscabral** [leafo/sticky-kit#32]
Is it possible to "stick" the element to the bottom of its parent? If yes, how?
Thanks!

**Comment by StanleyMlha** [comment]
:+1:

**Comment by zoffixznet** [comment]
+1

**Comment by Djules** [comment]
The plugin adds a CSS class to the element when it becomes stuck ("is_stuck" by default).
You can clear the top value and add bottom value in your stylesheet. 
e.g.
```css
.is_stuck {
    top: auto !important;
    bottom: 0;
}
```
