### ISSUE TITLE
Doesn't work if elastic scrolling is disabled via CSS

### ISSUE THREAD

**Issue by ben-eb** [leafo/sticky-kit#67]
Hi, first thanks for the plugin, I have found it to be very useful.

I've got a bit of an issue when applying the following CSS to my document (see [here](http://stackoverflow.com/questions/8150191/disable-elastic-scrolling-in-safari)) :

```css
html {
    height: 100%;
    width: 100%;
    overflow: hidden;
}

body {
    height: 100%;
    width: 100%;
    overflow: auto;
}
```

I'm writing a single page application that needs the elastic scrolling disabled. However with this CSS, I can't get sticky kit to work; I'm assuming that it's because the scroll context of the page is changed from the window to the body instead, but I have no real idea about how to fix this issue. Removing this CSS means that sticky kit will function as expected, but that's not ideal for my use case.

Any advice would be appreciated. :smiley:
